name = "example-kiribi"
compatibility_date = "2024-04-03"
main = "src/index.ts"

[[d1_databases]]
binding = "KIRIBI_DB"
database_name = "kiribi-db"
database_id = "40fc2a53-40b6-4a74-b713-d5190e17477f"
migrations_dir = './node_modules/kiribi/migrations'

[[queues.producers]]
binding = "KIRIBI_QUEUE"
queue = "kiribi-queue"

[[queues.consumers]]
queue = "kiribi-queue"
max_retries = 5

[[services]]
binding = "KIRIBI"
service = "example-kiribi"

[site]
bucket = "./node_modules/kiribi/client"

# Add queue processing jobs below

[[services]]
binding = "SLOW_JOB"
service = "example-kiribi"
entrypoint = "SlowJob"

[[services]]
binding = "FLAKY_JOB"
service = "example-kiribi"
entrypoint = "FlakyJob"

