name = "example-kiribi"
compatibility_date = "2024-04-03"
main = "src/index.ts"

[[d1_databases]]
binding = "KIRIBI_DB"
database_name = "example-kiribi-db"
database_id = "54d3aa4c-1b49-4d22-9b1c-4bfecaa98b53"
migrations_dir = './node_modules/kiribi/migrations'

[[queues.producers]]
binding = "KIRIBI_QUEUE"
queue = "example-kiribi-queue"

[[queues.consumers]]
queue = "example-kiribi-queue"
max_retries = 5

[[services]]
binding = "KIRIBI"
service = "example-kiribi"

[site]
bucket = "./node_modules/kiribi/client"

# Add queue processing jobs below

[[services]]
binding = "SLOW_JOB"
service = "example-kiribi"
entrypoint = "SlowJob"

[[services]]
binding = "FLAKY_JOB"
service = "example-kiribi"
entrypoint = "FlakyJob"

# initialize the database every hour
[triggers]
crons = [ "0 * * * *" ]
