name = "kiribi-dev"
compatibility_date = "2024-04-03"
main = "worker/index.ts"

[site]
bucket = "./client"

[[d1_databases]]
binding = "KIRIBI_DB"
database_name = "kiribi-db"
database_id = "40fc2a53-40b6-4a74-b713-d5190e17477f"

[[queues.producers]]
binding = "KIRIBI_QUEUE"
queue = "kiribi-queue"

[[queues.consumers]]
queue = "kiribi-queue"
max_retries = 5

[[services]]
binding = "KIRIBI"
service = "kiribi-dev"

[[services]]
binding = "SLOW_JOB"
service = "kiribi-dev"
entrypoint = "SlowJob"

[[services]]
binding = "FLAKY_JOB"
service = "kiribi-dev"
entrypoint = "FlakyJob"
